insert into public.recipes (slug, name, description, ingredients, instructions, image_url, tags)
values
  ('black-bean-enchiladas', 'Black Bean Enchiladas', 'Corn tortillas filled with spiced black beans and cheese, baked under smoky enchilada sauce and plated with cilantro-lime rice.', '[{"name":"vegetable oil","amount":"15ml"},{"name":"small onion","amount":"1","notes":"approximately 100g; finely chopped"},{"name":"garlic cloves","amount":"2","notes":"minced"},{"name":"ground cumin","amount":"5ml"},{"name":"chili powder","amount":"5ml"},{"name":"smoked paprika","amount":"2.5ml"},{"name":"canned black beans","amount":"2 x 400g cans","notes":"drained and rinsed"},{"name":"corn tortillas","amount":"12"},{"name":"shredded cheddar cheese","amount":"200g","notes":"plus extra for topping"},{"name":"canned red enchilada sauce","amount":"400g"},{"name":"salt","amount":"to taste"},{"name":"black pepper","amount":"to taste"},{"name":"fresh cilantro","amount":"30g","notes":"chopped, for garnish and rice"},{"name":"lime","amount":"1","notes":"cut into wedges, for garnish and rice"},{"name":"quick-cook white rice","amount":"200g","notes":"for side dish"}]', '1. Preheat your oven to 190°C. Lightly grease a 23x33 cm baking dish.
2. In a large pan or skillet, heat the *vegetable oil* over medium heat. Add the chopped *onion* and sauté for 5-7 minutes until softened. Add the minced garlic, *ground cumin*, *chili powder*, and *smoked paprika*, cooking for another minute until fragrant.
3. Stir in the drained and rinsed *black beans*. Cook for 5-7 minutes, using a fork or potato masher to mash about half of the beans. This creates a creamy, substantial filling. Season with *salt* and *black pepper* to taste.
4. Warm the *corn tortillas* slightly to make them pliable. You can do this in a microwave for 15-20 seconds or quickly in a dry pan. Spoon approximately 60 g of the *black bean* mixture and a sprinkle of shredded *cheese* into the center of each tortilla. Roll tightly and place seam-down in the prepared baking dish.
5. Pour the *enchilada sauce* evenly over the rolled *tortillas*. Top with the remaining shredded *cheese*.
6. Bake for 20-25 minutes, or until the *cheese* is melted and bubbly and the enchiladas are heated through.
7. While the enchiladas bake, cook the *quick-cook white rice* according to package directions. Once cooked, stir in half of the chopped *fresh cilantro* and a squeeze of *lime* juice from one of the lime wedges.
8. Serve the *black bean* enchiladas hot, garnished with the remaining *fresh cilantro* and *lime* wedges, alongside the cilantro-lime *rice*.', 'recipe-images/black-bean-enchiladas.jpg', array['mexican', 'vegetarian', 'glutenfree']),
  ('buffalo-cauliflower-wraps', 'Buffalo Cauliflower Wraps', 'Crispy cauliflower tossed in tangy buffalo sauce with crunchy slaw in soft tortillas, served with carrot and celery sticks.', '[{"name":"cauliflower","amount":"1 medium head","notes":"cut into bite-sized florets; about 600-700g"},{"name":"all-purpose flour","amount":"60g"},{"name":"cornstarch","amount":"15g"},{"name":"garlic powder","amount":"1 tsp"},{"name":"onion powder","amount":"1 tsp"},{"name":"smoked paprika","amount":"1/2 tsp"},{"name":"salt","amount":"1/2 tsp","notes":"plus more for seasoning"},{"name":"black pepper","amount":"1/4 tsp","notes":"plus more for seasoning"},{"name":"water","amount":"120ml"},{"name":"buffalo wing sauce","amount":"120ml","notes":"e.g., Frank''s RedHot"},{"name":"flour tortillas","amount":"8 medium","notes":"20 cm"},{"name":"green cabbage","amount":"250g","notes":"finely shredded"},{"name":"carrot","amount":"1 medium","notes":"shredded"},{"name":"vegan mayonnaise","amount":"60g"},{"name":"apple cider vinegar","amount":"15ml"},{"name":"maple syrup","amount":"5ml","notes":"or granulated sugar"},{"name":"celery sticks","amount":"for serving"},{"name":"carrot sticks","amount":"for serving"}]', '1. Preheat your oven to 200°C. Line a large baking sheet with parchment paper. In a large bowl, whisk together the *all-purpose flour*, *cornstarch*, *garlic powder*, *onion powder*, *smoked paprika*, 1/2 tsp *salt*, and 1/4 tsp *black pepper*. Gradually whisk in the *water* until a smooth, thick batter forms. Add the *cauliflower* florets to the batter and toss until each piece is evenly coated.
2. Spread the coated *cauliflower* in a single layer on the prepared baking sheet. Bake for 20-25 minutes, flipping the florets halfway through, until they are golden brown and crispy.
3. While the *cauliflower* bakes, prepare the slaw. In a medium bowl, combine the shredded *cabbage* and shredded *carrot*. In a small separate bowl, whisk together the *vegan mayonnaise*, *apple cider vinegar*, *maple syrup*, a pinch of *salt*, and a pinch of *black pepper*. Pour the dressing over the cabbage and carrot mixture and toss well to combine.
4. Once the *cauliflower* is crispy, remove it from the oven. Transfer the hot cauliflower back into the large bowl (or a clean one). Pour the *buffalo wing sauce* over the cauliflower and toss gently until all florets are thoroughly coated.
5. Warm the *flour* tortillas according to package directions (typically 15-30 seconds in the microwave, or briefly in a dry pan). Fill each warm tortilla with a generous portion of the buffalo *cauliflower* and a spoonful of the crunchy slaw.
6. Fold the *tortillas* into wraps and serve immediately with extra *carrot* and *celery sticks* on the side.', 'recipe-images/buffalo-cauliflower-wraps.jpg', array['american', 'vegan', 'spicy']),
  ('caprese-stuffed-portobellos', 'Caprese Stuffed Portobellos', 'Roasted mushroom caps filled with mozzarella, cherry tomatoes, and balsamic glaze, accompanied by herb-roasted baby potatoes.', '[{"name":"large portobello mushrooms","amount":"4","notes":"Stems removed, gills gently scraped out"},{"name":"baby potatoes","amount":"500g","notes":"Washed and halved"},{"name":"cherry tomatoes","amount":"200g","notes":"Halved"},{"name":"fresh mozzarella","amount":"125g","notes":"Ball or bocconcini, sliced or torn"},{"name":"olive oil","amount":"60ml","notes":"Divided"},{"name":"balsamic glaze","amount":"60ml","notes":"Store-bought or homemade"},{"name":"garlic","amount":"2 cloves","notes":"Minced"},{"name":"dried oregano","amount":"1 tsp"},{"name":"fresh basil","amount":"A few leaves","notes":"For garnish, optional"},{"name":"salt","amount":"To taste"},{"name":"black pepper","amount":"To taste"}]', '1. Preheat your oven to 200°C. In a large bowl, toss the halved *baby potatoes* with 30 ml of *olive oil*, minced *garlic*, *dried oregano*, *salt*, and *black pepper* until evenly coated. Spread the seasoned potatoes in a single layer on a large baking tray.
2. Roast the *potatoes* in the preheated oven for 15 minutes to give them a head start.
3. While the *potatoes* are roasting, prepare the *portobello mushrooms*. Brush the mushroom caps with the remaining 30 ml of *olive oil* and season lightly with *salt* and *pepper*. Slice the *cherry tomatoes* and *fresh mozzarella*.
4. After 15 minutes, carefully remove the baking tray from the oven. Arrange the prepared *portobello mushroom* caps, gill-side up, on the same tray alongside the *potatoes* (or use a second tray if needed). Fill each mushroom cap generously with the sliced *mozzarella* and halved *cherry tomatoes*.
5. Return the tray(s) to the oven and continue to roast for another 15-20 minutes, or until the *mushrooms* are tender, the cheese is melted and bubbly, and the *potatoes* are golden brown and cooked through.
6. Remove from the oven. Drizzle the Caprese stuffed portobellos with *balsamic glaze*. Garnish with *fresh basil* leaves if desired. Serve immediately with the herb-roasted *baby potatoes*.', 'recipe-images/caprese-stuffed-portobellos.jpg', array['italian', 'vegetarian', 'glutenfree']),
  ('chickpea-tikka-masala', 'Chickpea Tikka Masala', 'Creamy tomato curry with spiced chickpeas and warm garam masala, served with steamed basmati rice and cooling cucumber salad.', '[{"name":"vegetable oil","amount":"2 tbsp"},{"name":"onion","amount":"1 medium","notes":"finely chopped; approx. 150g"},{"name":"garlic","amount":"3 cloves","notes":"minced"},{"name":"fresh ginger","amount":"2 cm piece","notes":"grated"},{"name":"ground cumin","amount":"1 tsp"},{"name":"ground coriander","amount":"1 tsp"},{"name":"turmeric powder","amount":"0.5 tsp"},{"name":"chilli powder","amount":"0.5 tsp","notes":"adjust to taste"},{"name":"canned crushed tomatoes","amount":"400g"},{"name":"canned chickpeas","amount":"2 x 400g cans","notes":"drained and rinsed"},{"name":"full-fat coconut milk","amount":"200ml"},{"name":"garam masala","amount":"1 tsp"},{"name":"salt","amount":"to taste"},{"name":"sugar","amount":"0.5 tsp","notes":"optional, to balance acidity"},{"name":"fresh coriander","amount":"2 tbsp","notes":"chopped, for garnish"},{"name":"basmati rice","amount":"200g","notes":"for serving"},{"name":"cucumber","amount":"1 small","notes":"diced, for salad; approx. 150g"},{"name":"lemon juice","amount":"1 tbsp","notes":"for cucumber salad"}]', '1. Rinse the *basmati rice* thoroughly under cold water until the water runs clear. Place the rice in a small saucepan with 400 ml of water. Bring to a boil, then reduce heat to low, cover, and simmer for 12-15 minutes, or until all water is absorbed. Remove from heat and let stand, covered, for 5 minutes.
2. While the *rice* cooks, heat the *vegetable oil* in a large saucepan or pot over medium heat. Add the chopped *onion* and cook for 5-7 minutes, stirring occasionally, until softened and translucent.
3. Add the minced *garlic* and grated *ginger* to the pot. Cook for another 1 minute until fragrant. Stir in the *ground cumin*, *ground coriander*, *turmeric powder*, and *chilli powder*. Cook for 30 seconds, stirring constantly, until the spices are aromatic.
4. Pour in the *crushed tomatoes* and bring the mixture to a gentle simmer. Add the drained and rinsed *chickpeas*. Stir well, then reduce the heat to low, cover, and let simmer for 10 minutes, allowing the flavors to meld.
5. Stir in the *coconut milk* and *garam masala*. If using, add the *sugar* to balance the acidity of the *tomatoes*. Season with *salt* to taste. Continue to simmer gently, uncovered, for another 5 minutes, until the sauce has thickened slightly and is heated through.
6. While the curry simmers, prepare the *cucumber* salad: In a small bowl, combine the diced cucumber with the *lemon juice* and a pinch of *salt*. Toss gently.
7. Fluff the cooked *basmati rice* with a fork. Taste the *chickpea* Tikka *masala* and adjust seasoning if necessary.
8. Serve the *chickpea* Tikka *masala* hot with the steamed *basmati rice* and the refreshing *cucumber* salad. Garnish with fresh chopped *coriander*.', 'recipe-images/chickpea-tikka-masala.jpg', array['indian', 'vegan', 'glutenfree']),
  ('classic-beef-tacos', 'Classic Beef Tacos', 'Seasoned ground beef tucked into crispy corn shells with lettuce and cheddar, served alongside Mexican rice.', '[{"name":"lean ground beef","amount":"450g"},{"name":"taco seasoning mix","amount":"28g","notes":"Or homemade blend of chili powder, cumin, paprika, garlic powder, onion powder, salt, and pepper"},{"name":"water","amount":"160ml"},{"name":"crispy corn taco shells","amount":"12 shells"},{"name":"iceberg or romaine lettuce","amount":"1 small head","notes":"Shredded"},{"name":"cheddar cheese","amount":"170g","notes":"Shredded"},{"name":"vegetable oil","amount":"15ml","notes":"Optional, for browning beef if not lean enough"},{"name":"yellow onion","amount":"1/2 medium","notes":"Finely chopped, optional"}]', '1. In a large skillet over medium-high heat, brown the *ground beef* (and chopped *onion*, if using). If the beef is not lean, you may add a tbsp of *vegetable oil* to prevent sticking. Cook, breaking up the meat with a spoon, until no pink remains, about 5-7 minutes.
2. Drain any excess fat from the skillet. Stir in the *taco seasoning mix* and *water*. Bring the mixture to a simmer, then reduce heat to low and cook for 5-7 minutes, stirring occasionally, until the liquid has mostly absorbed and the *beef* is well-seasoned.
3. While the *beef* is simmering, prepare your toppings. Shred the *lettuce* and *cheddar cheese*, if not already pre-shredded. Set aside.
4. Preheat your oven to 160°C or follow package directions to warm the *taco shells*. Place the taco shells on a baking sheet and bake for 5-7 minutes, or until lightly crispy and warm. Alternatively, microwave them for 30-45 seconds until warm.
5. Assemble the tacos by spooning the seasoned *ground beef* into each warm *taco shell*. Top with shredded *lettuce* and shredded *cheddar cheese*. Serve immediately, optionally alongside quick Mexican rice.', 'recipe-images/classic-beef-tacos.jpg', array['mexican', 'beef', 'glutenfree']),
  ('coconut-curry-ramen', 'Coconut Curry Ramen', 'Fragrant coconut broth with ramen noodles, baby bok choy, and crispy tofu cubes, with a side of sesame cucumber salad.', '[{"name":"extra-firm tofu","amount":"400g","notes":"Pressed and cubed"},{"name":"ramen noodles","amount":"400g","notes":"Dried ramen without seasoning"},{"name":"full-fat coconut milk","amount":"400ml"},{"name":"vegetable broth","amount":"1 litre"},{"name":"red curry paste","amount":"40-60g","notes":"Adjust to taste"},{"name":"baby bok choy","amount":"4-6 heads","notes":"Halved lengthwise"},{"name":"garlic","amount":"3 cloves","notes":"Minced"},{"name":"fresh ginger","amount":"15g","notes":"Grated"},{"name":"yellow onion","amount":"1/2 medium","notes":"Finely diced"},{"name":"soy sauce","amount":"30ml","notes":"Use tamari for gluten-free"},{"name":"lime juice","amount":"15ml","notes":"From about 1/2 lime"},{"name":"vegetable oil","amount":"30ml","notes":"For tofu and sautéing"},{"name":"cucumber","amount":"1 large","notes":"Thinly sliced, for salad; 250g"},{"name":"rice vinegar","amount":"30ml","notes":"For salad"},{"name":"toasted sesame oil","amount":"15ml","notes":"For salad"},{"name":"sesame seeds","amount":"5g","notes":"For salad/garnish"},{"name":"fresh cilantro or green onions","amount":"Optional","notes":"For garnish"}]', '1. Press excess water from the *tofu* block. Cut into roughly 2 cm cubes. Heat half of the vegetable *oil* in a large pot or Dutch oven over medium-high heat. Add tofu cubes and cook, stirring occasionally, until golden brown and crispy on all sides, about 10-15 minutes. Remove tofu from the pot and set aside.
2. In the same pot, add the remaining *oil* if needed. Add diced *onion* and cook until softened, about 3-4 minutes. Stir in minced *garlic* and grated *ginger*, cooking for another minute until fragrant. Add *red curry paste* and cook, stirring constantly, for 1-2 minutes to toast the spices.
3. Pour in the *vegetable broth* and *coconut milk*. Bring to a gentle simmer, then reduce heat to low and let it simmer for 10-15 minutes to allow flavors to meld. Stir in *soy sauce* and *lime juice*. Taste and adjust seasonings as needed.
4. While the *broth* simmers, cook the *ramen noodles* according to package directions in a separate pot of boiling water. Drain well. Add the halved *baby bok choy* to the simmering curry broth during the last 2-3 minutes of cooking, just until wilted and tender-crisp.
5. In a small bowl, combine sliced *cucumber*, *rice vinegar*, *toasted sesame oil*, and *sesame seeds*. Toss gently to combine.
6. Divide the cooked *ramen noodles* among serving bowls. Ladle the hot coconut curry *broth* and *bok choy* over the noodles. Top each bowl with the crispy *tofu* cubes. Garnish with *fresh cilantro or green onions*, if desired. Serve immediately with the sesame *cucumber* salad on the side.', 'recipe-images/coconut-curry-ramen.jpg', array['fusion', 'vegan']),
  ('creamy-mushroom-risotto', 'Creamy Mushroom Risotto', 'Arborio rice simmered with garlic, mushrooms, and parmesan until silky, paired with roasted asparagus spears for crunch.', '[{"name":"arborio rice","amount":"300g"},{"name":"cremini or button mushrooms","amount":"250g","notes":"sliced"},{"name":"vegetable broth","amount":"1 litre","notes":"warm"},{"name":"yellow onion","amount":"1 medium","notes":"finely chopped"},{"name":"garlic","amount":"2 cloves","notes":"minced"},{"name":"parmesan cheese","amount":"80g","notes":"freshly grated"},{"name":"olive oil","amount":"2 tbsp"},{"name":"unsalted butter","amount":"30g"},{"name":"dry white wine","amount":"120ml","notes":"such as Pinot Grigio (optional)"},{"name":"asparagus","amount":"300g","notes":"trimmed"},{"name":"fresh parsley","amount":"2 tbsp","notes":"chopped, for garnish"},{"name":"lemon","amount":"1/2","notes":"for serving with asparagus"},{"name":"salt","amount":"To taste"},{"name":"black pepper","amount":"To taste"}]', '1. Preheat oven to 200°C. Toss the trimmed *asparagus* spears with 1 tbsp of *olive oil*, a pinch of *salt*, and *black pepper* on a baking tray. Roast for 10-12 minutes until tender-crisp. Set aside.
2. In a large, heavy-bottomed pot or Dutch oven, melt 15 g of *unsalted butter* with the remaining 1 tbsp of *olive oil* over medium heat. Add the chopped *yellow onion* and cook until softened and translucent, about 5 minutes. Add the minced *garlic* and cook for another minute until fragrant.
3. Add the *arborio rice* to the pot and stir constantly for 2 minutes until the edges of the grains are translucent but the center is still opaque. If using, pour in the *dry white wine* and stir until it has been completely absorbed by the rice.
4. Begin adding the warm *vegetable broth*, one ladleful (about 120 ml) at a time, stirring frequently. Wait until each addition of broth is almost completely absorbed before adding the next. After about 10 minutes of adding broth, stir in the sliced *cremini or button mushrooms*.
5. Continue adding *vegetable broth* and stirring for another 10-15 minutes, or until the *arborio rice* is creamy and al dente (cooked through but still firm to the bite). You may not need all of the broth. Remove the pot from the heat.
6. Stir in the remaining 15 g of *unsalted butter* and the grated *parmesan cheese* until melted and fully incorporated. season with *salt* and *black pepper* to taste. Let the risotto rest for 2 minutes, covered.
7. Serve the creamy *mushroom* risotto immediately, garnished with chopped *fresh parsley* and accompanied by the roasted *asparagus* spears. A squeeze of *lemon* over the asparagus is highly recommended.', 'recipe-images/creamy-mushroom-risotto.jpg', array['italian', 'vegetarian', 'glutenfree']),
  ('gochujang-glazed-chicken-thighs', 'Gochujang Glazed Chicken Thighs', 'Sweet-heat gochujang glaze on roasted chicken thighs with sesame seeds, paired with kimchi fried rice.', '[{"name":"boneless, skinless chicken thighs","amount":"680g"},{"name":"gochujang","amount":"60g","notes":"Korean chili paste"},{"name":"soy sauce","amount":"2 tbsp"},{"name":"honey","amount":"2 tbsp"},{"name":"rice vinegar","amount":"1 tbsp"},{"name":"minced garlic","amount":"2 cloves"},{"name":"grated fresh ginger","amount":"1 tsp"},{"name":"sesame oil","amount":"1 tsp","notes":"plus more for rice"},{"name":"toasted sesame seeds","amount":"1 tbsp","notes":"for garnish"},{"name":"cooked day-old rice","amount":"600g"},{"name":"kimchi, chopped","amount":"200g"},{"name":"kimchi juice","amount":"2 tbsp"},{"name":"large egg","amount":"1"},{"name":"green onions, sliced","amount":"2","notes":"for garnish"},{"name":"vegetable oil","amount":"1 tbsp","notes":"for rice"}]', '1. Preheat the oven to 200°C. In a medium bowl, whisk together *gochujang*, *soy sauce*, *honey*, *rice* vinegar, *minced garlic*, grated *ginger*, and 1 tsp sesame *oil* to create the glaze.
2. Pat *chicken thighs* dry. Place them on a foil-lined baking sheet. Brush about half of the *gochujang* glaze generously over both sides of the chicken. Bake for 15 minutes.
3. While the chicken bakes, prepare the kimchi fried rice. Heat 1 tbsp *vegetable oil* in a large skillet or wok over medium-high heat. Add the *chopped* kimchi and sauté for 2-3 minutes. Add the *day-old rice* and *kimchi juice*, stirring to combine and break up any clumps. Cook for 5-7 minutes, stirring occasionally, until the rice is heated through and slightly crispy. Push rice to one side, crack the *egg* into the empty side, scramble, then mix into the rice. Stir in a dash of *sesame oil*.
4. After 15 minutes, remove chicken from the oven. Brush the remaining glaze over the chicken. Return to the oven and bake for another 10-15 minutes, or until the chicken is cooked through (internal temperature reaches 74°C) and the glaze is sticky and lacquered.
5. Remove chicken from oven. Let rest for a few minutes. Serve the *gochujang* Glazed *chicken thighs* over the glossy *kimchi* fried *rice*, garnished with *toasted sesame seeds* and *sliced* green onions.', 'recipe-images/gochujang-glazed-chicken-thighs.jpg', array['korean', 'chicken', 'spicy']),
  ('greek-stuffed-peppers', 'Greek Stuffed Peppers', 'Bell peppers baked with herbed rice, feta, and olives, served with lemony cucumber salad.', '[{"name":"bell peppers","amount":"4 large","notes":"any color, halved lengthwise, seeds and membranes removed"},{"name":"uncooked long-grain white rice","amount":"200g"},{"name":"vegetable broth","amount":"500ml","notes":"divided"},{"name":"olive oil","amount":"2 tbsp"},{"name":"small onion","amount":"1","notes":"finely chopped"},{"name":"garlic cloves","amount":"2","notes":"minced"},{"name":"tomato paste","amount":"2 tbsp"},{"name":"canned diced tomatoes","amount":"400g","notes":"drained"},{"name":"dried oregano","amount":"1 tsp"},{"name":"feta cheese","amount":"60g","notes":"crumbled"},{"name":"kalamata olives","amount":"40g","notes":"pitted and chopped"},{"name":"fresh parsley","amount":"15g","notes":"chopped"},{"name":"salt","amount":"to taste"},{"name":"black pepper","amount":"to taste"},{"name":"cucumber","amount":"1 medium","notes":"diced, for salad"},{"name":"lemon juice","amount":"2 tbsp","notes":"for salad"},{"name":"fresh dill","amount":"1 tbsp","notes":"chopped, for salad (optional)"}]', '1. Preheat your oven to 190°C. Lightly grease a 23x33 cm baking dish. Prepare the *bell peppers* by halving them lengthwise and removing the seeds and membranes.
2. In a medium saucepan, combine the uncooked *rice* with 375 ml of *vegetable broth*. Bring to a boil, then reduce heat to low, cover, and simmer for 10 minutes. The rice will be partially cooked.
3. While the *rice* cooks, heat *olive* oil in a large skillet over medium heat. Add the chopped *onion* and cook until softened, about 5 minutes. Add the minced garlic and *tomato paste*, cooking for another minute until fragrant. Stir in the drained *diced tomatoes* and *dried oregano*, cooking for 2-3 minutes.
4. Remove the skillet from heat. Stir in the partially cooked *rice*, crumbled *feta cheese*, chopped *kalamata olives*, and *fresh parsley*. Season the filling with *salt* and black *pepper* to taste. Mix well to combine.
5. Arrange the *pepper* halves in the prepared baking dish. Spoon the *rice* mixture evenly into each pepper half. Pour the remaining 125 ml of *vegetable broth* into the bottom of the baking dish. Cover the dish tightly with foil.
6. Bake for 25 minutes. Remove the foil and continue baking for another 10-15 minutes, or until the *peppers* are tender and the filling is heated through and slightly golden on top. While the peppers bake uncovered, prepare the quick *cucumber* salad by combining diced cucumber, *lemon juice*, chopped *fresh dill* (if using), and a pinch of *salt* and pepper in a small bowl.
7. Serve the hot stuffed *peppers* immediately with the refreshing lemony *cucumber* salad on the side.', 'recipe-images/greek-stuffed-peppers.jpg', array['greek', 'vegetarian', 'glutenfree']),
  ('lemon-garlic-salmon', 'Lemon Garlic Salmon', 'Oven-baked salmon fillets with lemon butter and fresh parsley, served alongside roasted baby potatoes and green beans.', '[{"name":"salmon fillets","amount":"4 fillets","notes":"about 170g each"},{"name":"baby potatoes","amount":"680g","notes":"halved"},{"name":"green beans","amount":"450g","notes":"trimmed"},{"name":"lemon","amount":"1 large","notes":"half sliced, half juiced"},{"name":"garlic","amount":"4 cloves","notes":"minced"},{"name":"unsalted butter","amount":"4 tbsp","notes":"melted; 56g"},{"name":"fresh parsley","amount":"15g","notes":"chopped"},{"name":"olive oil","amount":"2 tbsp"},{"name":"salt","amount":"1 tsp"},{"name":"black pepper","amount":"1/2 tsp"}]', '1. Preheat your oven to 200°C. On a large baking sheet, toss the halved *baby potatoes* with 1 tbsp of *olive oil*, 1/2 tsp of *salt*, and 1/4 tsp of *black pepper*. Roast for 15 minutes.
2. While the *potatoes* roast, prepare the *lemon*-*garlic* *butter*. In a small bowl, combine the melted butter, minced garlic, the juice from half a lemon, and half of the chopped *fresh parsley*. Season with a pinch of *salt* and *pepper*.
3. After 15 minutes, remove the baking sheet from the oven. Push the roasted *potatoes* to one side of the sheet. Add the trimmed *green beans* to the empty side, tossing them with the remaining 1 tbsp of *olive oil*, 1/4 tsp of *salt*, and 1/8 tsp of *black pepper*.
4. Place the *salmon fillets*, skin-side down if applicable, on the baking sheet among the vegetables. Spoon the *lemon*-*garlic* *butter* mixture evenly over each salmon fillet. Top each fillet with a thin lemon slice.
5. Return the baking sheet to the oven and bake for another 12-18 minutes, or until the salmon is cooked through and flakes easily with a fork, and the vegetables are tender-crisp. Cooking time will vary based on salmon thickness.
6. Garnish the entire dish with the remaining *fresh parsley* before serving immediately.', 'recipe-images/lemon-garlic-salmon.jpg', array['american', 'seafood', 'glutenfree']),
  ('lentil-bolognese', 'Lentil Bolognese', 'Hearty red lentils simmered in tomato basil sauce over pasta, finished with a side of garlicky sautéed spinach.', '[{"name":"red lentils","amount":"200g","notes":"rinsed"},{"name":"pasta","amount":"350g","notes":"e.g., spaghetti, penne"},{"name":"canned chopped tomatoes","amount":"400g"},{"name":"vegetable stock","amount":"300ml"},{"name":"onion","amount":"1 medium","notes":"finely chopped"},{"name":"carrot","amount":"1 medium","notes":"finely chopped"},{"name":"celery stalk","amount":"1","notes":"finely chopped"},{"name":"garlic cloves","amount":"3","notes":"minced, for bolognese"},{"name":"olive oil","amount":"2 tbsp"},{"name":"dried oregano","amount":"1 tsp"},{"name":"dried basil","amount":"1 tsp"},{"name":"salt","amount":"To taste"},{"name":"black pepper","amount":"To taste"},{"name":"fresh spinach","amount":"200g"},{"name":"garlic cloves","amount":"2","notes":"thinly sliced, for spinach"}]', '1. Prepare your vegetables: finely chop the *onion*, *carrot*, and celery. Mince the 3 *garlic cloves* for the bolognese sauce.
2. Heat 1 tbsp of *olive oil* in a large pot or deep pan over medium heat. Add the chopped *onion*, *carrot*, and celery. Sauté for 5-7 minutes until softened.
3. Add the minced garlic, *dried oregano*, and *dried basil* to the pot. Cook for another 1 minute until fragrant, stirring constantly.
4. Stir in the rinsed *red lentils*, *canned chopped tomatoes*, and *vegetable stock*. Bring the mixture to a gentle simmer. Reduce the heat to low, cover the pot, and let it simmer for 15-20 minutes, or until the lentils are tender and the sauce has thickened. Stir occasionally to prevent sticking. Season generously with *salt* and *black pepper* to taste.
5. While the bolognese simmers, bring a large pot of well-salted water to a rolling boil. Add the *pasta* and cook according to package directions until al dente. Drain the pasta, reserving about 60 ml of the pasta cooking water.
6. In a separate frying pan, heat the remaining 1 tbsp of *olive oil* over medium heat. Add the 2 thinly sliced *garlic cloves* and cook for 30 seconds until fragrant. Add the *fresh spinach* and sauté for 2-3 minutes until completely wilted. Season with a pinch of *salt*.
7. Serve the hearty *lentil* bolognese over the cooked *pasta*. If the sauce is too thick, stir in a splash of the reserved pasta water to reach your desired consistency. Serve with the garlicky sautéed *spinach* on the side.', 'recipe-images/lentil-bolognese.jpg', array['italian', 'vegan']),
  ('margherita-pizza', 'Margherita Pizza', 'Blistered crust layered with ripe tomatoes, creamy mozzarella, and garden basil for a comforting pizzeria-style pie; serve with a peppery arugula salad dressed in lemon vinaigrette.', '[{"name":"pizza dough","amount":"250-300g","notes":"Store-bought fresh pizza dough"},{"name":"canned crushed tomatoes","amount":"200g","notes":"Look for San Marzano if possible, or good quality crushed tomatoes"},{"name":"fresh mozzarella","amount":"125g","notes":"Drained and sliced into thin rounds"},{"name":"fresh basil leaves","amount":"15g","notes":"About 10-12 large leaves"},{"name":"extra virgin olive oil","amount":"30ml","notes":"Plus extra for drizzling"},{"name":"garlic","amount":"1 clove","notes":"Minced, for the sauce"},{"name":"salt","amount":"5g","notes":"To taste, for sauce and pizza"},{"name":"black pepper","amount":"2g","notes":"Freshly ground, to taste"},{"name":"arugula","amount":"50g","notes":"For the side salad"},{"name":"lemon","amount":"1 whole","notes":"For the salad dressing"},{"name":"flour","amount":"10g","notes":"for dusting the work surface"}]', '1. Preheat your oven to its highest setting, ideally around 250°C, with a pizza stone or baking steel inside if you have one. If not, a regular baking tray will work.
2. Prepare the tomato sauce: In a small bowl, combine the *crushed tomatoes*, minced *garlic*, 15 ml of *olive oil*, and a pinch of *salt*. Stir well and set aside.
3. Lightly dust a work surface with *flour* and gently stretch the *pizza dough* or use parchment paper to your desired thickness, aiming for a round shape about 25-30 cm in diameter.
4. Carefully transfer the *dough* to the hot pizza stone or baking tray. Spread the tomato sauce evenly over the dough, leaving a small border for the crust. Distribute the sliced *mozzarella* over the sauce.
5. Bake for 8-12 minutes, or until the crust is golden brown and blistered, and the cheese is melted and bubbly. Cooking time may vary depending on your oven.
6. While the pizza bakes, prepare the *arugula* salad: In a medium bowl, combine the arugula. In a separate small bowl, whisk together the juice of half a *lemon*, the remaining 15 ml of *olive oil*, a pinch of *salt*, and a dash of *black pepper* to create a simple vinaigrette.
7. Once the pizza is out of the oven, immediately scatter the *fresh basil leaves* over the hot cheese. Drizzle with a little *extra virgin olive oil* if desired. Slice and serve hot with the dressed arugula salad on the side.', 'recipe-images/margherita-pizza.jpg', array['italian', 'vegetarian']),
  ('mediterranean-quinoa-bowl', 'Mediterranean Quinoa Bowl', 'Herb quinoa with cucumber, tomato, olives, and lemon tahini dressing alongside lemon-herb cucumber salad.', '[{"name":"quinoa","amount":"200g"},{"name":"vegetable stock","amount":"400ml"},{"name":"fresh parsley","amount":"15g","notes":"finely chopped"},{"name":"fresh mint","amount":"5g","notes":"finely chopped"},{"name":"olive oil","amount":"30ml","notes":"divided"},{"name":"salt","amount":"5g","notes":"divided"},{"name":"tahini","amount":"60ml"},{"name":"lemon juice","amount":"45ml","notes":"freshly squeezed, divided"},{"name":"garlic","amount":"1 clove","notes":"minced"},{"name":"cold water","amount":"60-90ml","notes":"for dressing, adjust for consistency"},{"name":"black pepper","amount":"1.5g","notes":"freshly ground, divided"},{"name":"cherry tomatoes","amount":"250g","notes":"halved"},{"name":"cucumber","amount":"350g","notes":"150g diced for bowl, 200g thinly sliced for salad"},{"name":"kalamata olives","amount":"80g","notes":"pitted and halved"},{"name":"red onion","amount":"50g","notes":"thinly sliced"},{"name":"canned chickpeas","amount":"400g can","notes":"rinsed and drained"},{"name":"fresh dill","amount":"5g","notes":"finely chopped"}]', '1. Rinse *quinoa* thoroughly under *cold water*. In a medium saucepan, combine the rinsed quinoa, *vegetable stock*, 5 ml *olive* oil, and 2 g *salt*. Bring to a boil, then reduce heat to low, cover, and simmer for 15 minutes, or until all liquid is absorbed. Remove from heat and let stand, covered, for 5 minutes. Fluff with a fork and stir in chopped *parsley* and *mint*.
2. While *quinoa* cooks, prepare the Lemon *tahini* Dressing: Whisk together tahini, 30 ml *lemon juice*, minced *garlic*, 15 ml *olive* oil, 2 g *salt*, and 1 g *black pepper* in a small bowl. Gradually add *cold water*, starting with 60 ml, whisking until smooth and desired consistency is reached (add up to 30 ml more water if needed).
3. Prepare the main bowl components: In a large bowl, combine the halved *cherry tomatoes*, 150 g diced *cucumber*, halved *kalamata olives*, thinly sliced *red onion*, and rinsed *chickpeas*.
4. Prepare the Lemon-Herb *cucumber* Salad: In a separate medium bowl, combine the 200 g thinly sliced cucumber, 15 ml *lemon juice*, chopped *dill*, 10 ml *olive* oil, 1 g *salt*, and 0.5 g *black pepper*. Toss gently to combine.
5. Assemble the bowls: Divide the herb *quinoa* among serving bowls. Top each with a generous portion of the mixed bowl components. Drizzle generously with the *lemon* *tahini* dressing. Serve immediately with the lemon-herb *cucumber* salad on the side.', 'recipe-images/mediterranean-quinoa-bowl.jpg', array['mediterranean', 'vegan', 'glutenfree']),
  ('panko-crusted-cod', 'Panko-Crusted Cod', 'Flaky cod baked with crispy breadcrumbs and lemon zest, served with garlic mashed potatoes and steamed peas.', '[{"name":"cod fillets","amount":"450g","notes":"about 2-3 fillets, 2.5 cm thick"},{"name":"panko breadcrumbs","amount":"80g"},{"name":"lemon","amount":"1 large","notes":"for zest and juice"},{"name":"olive oil","amount":"2 tbsp"},{"name":"salt","amount":"1 tsp","notes":"divided"},{"name":"black pepper","amount":"1/2 tsp","notes":"divided"},{"name":"russet potatoes","amount":"680g","notes":"peeled and quartered"},{"name":"garlic","amount":"2 cloves","notes":"minced"},{"name":"milk","amount":"60ml","notes":"whole milk or half-and-half"},{"name":"butter","amount":"2 tbsp"},{"name":"frozen peas","amount":"150g"}]', '1. Preheat the oven to 200°C. Place quartered *potatoes* in a medium pot, cover with cold water by about 2.5 cm, and add 1/2 tsp *salt*. Bring to a boil, then reduce heat and simmer until very tender, about 15-20 minutes.
2. While *potatoes* cook, pat *cod fillets* dry with paper towels. Season both sides with 1/2 tsp *salt* and 1/4 tsp *black pepper*. In a shallow dish, combine *panko breadcrumbs*, the zest of 1 *lemon*, and 1/4 tsp black pepper. Drizzle cod fillets with 1 tbsp *olive oil*, then dredge each fillet in the panko mixture, pressing gently to ensure a golden crunchy coating adheres.
3. Place coated *cod fillets* on a lightly oiled baking sheet. Bake for 12-15 minutes, or until the cod is opaque and flakes easily with a fork, and the panko is golden brown. While cod bakes, drain cooked *potatoes*. Return to the hot pot. Add minced *garlic*, remaining 1 tbsp *olive oil*, *butter*, and *milk*. Mash until silky smooth, seasoning with additional *salt* and *pepper* to taste.
4. In a small saucepan, bring a small amount of water to a boil. Add *frozen peas* and steam for 3-4 minutes, or until tender-crisp. Drain well. Serve the panko-crusted cod immediately with the silky *garlic* mashed *potatoes* and steamed peas, garnished with fresh *lemon* wedges if desired.', 'recipe-images/panko-crusted-cod.jpg', array['american', 'seafood', 'glutenfree']),
  ('roasted-red-pepper-pasta', 'Roasted Red Pepper Pasta', 'Silky roasted red pepper sauce tossed with al dente pasta, fresh herbs, and toasted pine nuts, served with balsamic-dressed rocket.', '[{"name":"pasta","amount":"400g","notes":"e.g., spaghetti, fettuccine"},{"name":"jarred roasted red peppers","amount":"450g","notes":"drained weight"},{"name":"onion","amount":"1 medium","notes":"finely chopped"},{"name":"garlic","amount":"3 cloves","notes":"minced"},{"name":"olive oil","amount":"30ml"},{"name":"vegetable stock","amount":"100ml","notes":"or reserved pasta water"},{"name":"reserved pasta water","amount":"200ml","notes":"starchy cooking water saved from the pasta"},{"name":"fresh basil","amount":"30g","notes":"roughly chopped, plus extra for garnish"},{"name":"pine nuts","amount":"30g"},{"name":"parmesan cheese","amount":"50g","notes":"freshly grated, optional"},{"name":"salt","amount":"to taste"},{"name":"black pepper","amount":"to taste"},{"name":"rocket","amount":"100g","notes":"for serving"},{"name":"balsamic vinegar","amount":"15ml","notes":"for serving"}]', '1. Heat a small dry pan over medium heat. Add the *pine nuts* and toast for 2-3 minutes, stirring frequently, until golden brown and fragrant. Remove from the pan and set aside.
2. Bring a large pot of salted water to a rolling boil. Add the *pasta* and cook according to package directions until al dente. Before draining, reserve the *reserved pasta water*. Drain the pasta and set aside.
3. While the *pasta* cooks, heat the *olive oil* in a large saucepan or deep frying pan over medium heat. Add the chopped *onion* and cook for 5-7 minutes until softened and translucent. Add the minced *garlic* and cook for another minute until fragrant. Add the drained *jarred roasted red peppers* to the pan and cook for 2-3 minutes, stirring occasionally.
4. Carefully transfer the roasted *pepper* mixture from the pan to a blender. Add the *vegetable stock*, or a splash of *reserved pasta water* for a lighter sauce. Blend until completely smooth and creamy. Season the sauce with *salt* and *black pepper* to taste.
5. Return the sauce to the saucepan over low heat. Add the cooked *pasta* and toss to coat evenly. If the sauce is too thick, add a little more *reserved pasta water* until it reaches your desired consistency. Stir in the chopped *fresh basil* and the grated *parmesan cheese*.
6. Divide the *pasta* among serving plates. Garnish with the toasted *pine nuts* and *fresh basil*. In a small bowl, toss the *rocket* with a drizzle of *olive oil* and *balsamic vinegar*, then serve alongside the pasta.', 'recipe-images/roasted-red-pepper-pasta.jpg', array['italian', 'vegetarian']),
  ('spinach-ricotta-stuffed-shells', 'Spinach & Ricotta Stuffed Shells', 'Jumbo pasta shells packed with herbed ricotta and spinach, baked in marinara and served with a crisp romaine salad.', '[{"name":"jumbo pasta shells","amount":"250g","notes":"about 20-24 shells"},{"name":"ricotta cheese","amount":"500g","notes":"full-fat or part-skim"},{"name":"fresh spinach","amount":"200g","notes":"or 100g frozen, thawed and squeezed dry"},{"name":"marinara sauce","amount":"680g","notes":"1 jar"},{"name":"mozzarella cheese","amount":"150g","notes":"shredded"},{"name":"parmesan cheese","amount":"50g","notes":"grated"},{"name":"large egg","amount":"1","notes":"beaten"},{"name":"garlic","amount":"2 cloves","notes":"minced"},{"name":"dried oregano","amount":"1 tsp"},{"name":"fresh parsley","amount":"15g","notes":"finely chopped, or 1 tbsp dried parsley"},{"name":"salt","amount":"0.5 tsp"},{"name":"black pepper","amount":"0.25 tsp"},{"name":"olive oil","amount":"1 tbsp","notes":"for greasing"}]', '1. Preheat oven to 190°C. Lightly grease a 23cm x 33cm baking dish with 1 tbsp of *olive oil*. If using *fresh spinach*, quickly wilt it in a pan over medium heat, then squeeze out excess water and roughly chop. If using frozen, thaw and squeeze dry, then chop.
2. Cook the *jumbo pasta shells* according to package directions until al dente. Drain well and rinse with cold water to prevent sticking. Lay them out on a clean surface or baking sheet to cool slightly.
3. In a large bowl, combine the ricotta *cheese*, wilted and chopped *spinach*, beaten *egg*, minced *garlic*, *dried oregano*, chopped *parsley*, 0.5 tsp *salt*, and 0.25 tsp *black pepper*. Mix thoroughly until all ingredients are well combined.
4. Spread half of the *marinara sauce* evenly over the bottom of the prepared baking dish. Carefully stuff each cooked *pasta shell* with approximately 1-2 tbsp of the ricotta-*spinach* mixture. Arrange the stuffed shells in a single layer in the baking dish.
5. Pour the remaining *marinara sauce* over the stuffed *shells*, ensuring they are mostly covered. Sprinkle generously with the shredded *mozzarella cheese* and grated *parmesan cheese*.
6. Bake for 25-30 minutes, or until the *cheese* is melted and bubbly and the *sauce* is heated through. If desired, broil for the last 2-3 minutes for a golden-brown top.
7. Let the *shells* rest for 5 minutes before serving. Serve hot, perhaps with a simple crisp romaine salad dressed with vinaigrette for a complete meal.', 'recipe-images/spinach-ricotta-stuffed-shells.jpg', array['italian', 'vegetarian']),
  ('sweet-potato-black-bean-tacos', 'Sweet Potato & Black Bean Tacos', 'Roasted sweet potato cubes and black beans piled into warm tortillas with lime crema, paired with charred street-corn salad.', '[{"name":"sweet potatoes","amount":"600g","notes":"peeled and diced into 1.5 cm cubes"},{"name":"black beans","amount":"400g can","notes":"rinsed and drained"},{"name":"corn","amount":"340g can or 340g frozen","notes":"drained if canned, thawed if frozen"},{"name":"red onion","amount":"1 small","notes":"finely diced"},{"name":"fresh cilantro","amount":"30g","notes":"chopped, plus extra for garnish"},{"name":"limes","amount":"2-3","notes":"1 juiced and zested for crema, 1-2 juiced for corn salad and serving"},{"name":"olive oil","amount":"30ml","notes":"plus extra for charring corn"},{"name":"chili powder","amount":"10ml","notes":"divided; 2 tsp"},{"name":"ground cumin","amount":"10ml","notes":"divided; 2 tsp"},{"name":"smoked paprika","amount":"5ml","notes":"1 tsp"},{"name":"salt","amount":"5ml","notes":"plus more to taste; 1 tsp"},{"name":"black pepper","amount":"2.5ml","notes":"0.5 tsp"},{"name":"sour cream","amount":"120ml","notes":"or a vegan alternative for a plant-based option"},{"name":"corn tortillas","amount":"12","notes":"small, for gluten-free option"}]', '1. Preheat your oven to 200°C. In a large bowl, toss the diced *sweet potatoes* with 15 ml of *olive oil*, 5 ml of *chili powder*, 5 ml of *ground cumin*, the *smoked paprika*, 2.5 ml of *salt*, and all of the *black pepper*. Spread them in a single layer on a baking tray.
2. Roast the *sweet potatoes* for 20-25 minutes, or until tender and lightly caramelized, flipping halfway through. During the last 5 minutes of roasting, add the rinsed *black beans* to the tray with the sweet potatoes to warm through.
3. While the *sweet potatoes* roast, prepare the charred street-*corn* salad. Heat a frying pan over medium-high heat with a drizzle of *olive oil*. Add the corn and cook for 5-7 minutes, stirring occasionally, until some kernels are lightly charred. Transfer to a bowl and mix with the diced *red onion*, 20 g of chopped *cilantro*, the juice of one *lime*, the remaining 5 ml of *chili powder*, and 5 ml of *ground cumin*. Season with *salt* to taste.
4. For the *lime* crema, combine the *sour cream* (or vegan alternative) in a small bowl with the zest and juice of one lime and 2.5 ml of *salt*. Mix well until smooth.
5. Warm the *corn tortillas* according to package directions, either in a dry pan, microwave, or wrapped in foil in the oven for a few minutes.
6. Assemble the tacos by spooning the roasted sweet potato and *black bean* mixture into the warm *tortillas*. Top with a generous dollop of *lime* crema, a spoonful of the charred street-*corn* salad, and a sprinkle of *fresh cilantro*. Serve immediately with extra lime wedges.', 'recipe-images/sweet-potato-black-bean-tacos.jpg', array['mexican', 'vegan', 'glutenfree']),
  ('teriyaki-chicken-bowls', 'Teriyaki Chicken Bowls', 'Sweet-savory teriyaki chicken over rice with broccoli and carrots, paired with miso soup.', '[{"name":"boneless, skinless chicken thighs","amount":"680g","notes":"Cut into 2.5 cm pieces"},{"name":"soy sauce","amount":"120ml"},{"name":"mirin","amount":"60ml"},{"name":"brown sugar","amount":"2 tbsp"},{"name":"garlic","amount":"2 cloves","notes":"Minced"},{"name":"fresh ginger","amount":"1 tbsp","notes":"Grated"},{"name":"cornstarch","amount":"1 tbsp"},{"name":"water","amount":"2 tbsp","notes":"For cornstarch slurry"},{"name":"broccoli","amount":"1 head","notes":"Cut into florets"},{"name":"carrots","amount":"2 medium","notes":"Peeled and sliced"},{"name":"white rice","amount":"360g uncooked"},{"name":"water","amount":"960ml","notes":"For cooking rice"},{"name":"vegetable oil","amount":"1 tbsp"},{"name":"green onions","amount":"2","notes":"Sliced, for garnish"},{"name":"sesame seeds","amount":"1 tsp","notes":"For garnish"}]', '1. Cook the rice: Rinse *white rice* thoroughly. Combine rice and 960 ml of *water* in a medium saucepan. Bring to a boil, then reduce heat to low, cover, and simmer for 15-18 minutes, or until all water is absorbed. Remove from heat and let stand, covered, for 5 minutes before fluffing with a fork.
2. Prepare teriyaki sauce: In a medium bowl, whisk together *soy sauce*, *mirin*, *brown sugar*, minced *garlic*, and grated *ginger*. Set aside 2 tbsp of this mixture in a separate small bowl for later.
3. Cook chicken: Heat *vegetable oil* in a large skillet or wok over medium-high heat. Add the chicken pieces and cook for 5-7 minutes, stirring occasionally, until browned on all sides and cooked through. Remove chicken from the skillet and set aside.
4. Steam vegetables: While the chicken cooks, steam the *broccoli* florets and sliced *carrots* in a steamer basket over boiling *water* for 5-7 minutes, or until perfectly tender-crisp. Alternatively, microwave with a splash of water until desired tenderness.
5. Create the glossy glaze: Pour the main teriyaki *sauce* mixture (from Step 2) into the skillet. Bring to a simmer over medium heat. In the small bowl with the reserved teriyaki mixture, whisk in the *cornstarch* until smooth. Pour this cornstarch slurry into the simmering sauce, whisking constantly. Cook for 1-2 minutes, until the sauce thickens into a warm glossy glaze.
6. Combine and serve: Return the cooked chicken to the skillet with the thickened teriyaki glaze and toss to coat thoroughly. To assemble the bowls, divide the cooked *rice* among serving bowls. Top with the warm, glazed teriyaki chicken and the perfectly steamed *broccoli* and *carrots*. Garnish with sliced *green onions* and *sesame seeds*. Serve immediately, optionally alongside a quick instant miso soup.', 'recipe-images/teriyaki-chicken-bowls.jpg', array['japanese', 'chicken']),
  ('veggie-pad-thai', 'Veggie Pad Thai', 'Rice noodles tossed with tamarind sauce, tofu, and crisp vegetables, plated alongside a fresh cucumber-lime ribbon salad.', '[{"name":"rice stick noodles","amount":"200g","notes":"medium width"},{"name":"extra-firm tofu","amount":"250g","notes":"pressed and cut into 1.5 cm cubes"},{"name":"carrot","amount":"1 large","notes":"julienned"},{"name":"red bell pepper","amount":"1 medium","notes":"thinly sliced"},{"name":"broccoli florets","amount":"150g","notes":"small"},{"name":"bean sprouts","amount":"100g","notes":"fresh"},{"name":"spring onions","amount":"3","notes":"sliced into 2.5 cm pieces"},{"name":"garlic","amount":"2 cloves","notes":"minced"},{"name":"vegetable oil","amount":"2 tbsp"},{"name":"tamarind paste","amount":"2 tbsp","notes":"unsweetened"},{"name":"soy sauce","amount":"3 tbsp"},{"name":"maple syrup","amount":"2 tbsp"},{"name":"rice vinegar","amount":"1 tbsp"},{"name":"crushed roasted peanuts","amount":"50g","notes":"for garnish"},{"name":"fresh lime","amount":"1","notes":"cut into wedges, for garnish"},{"name":"fresh coriander","amount":"15g","notes":"chopped, for garnish"},{"name":"cucumber","amount":"1 medium","notes":"for ribbon salad"},{"name":"lime juice","amount":"1 tbsp","notes":"for ribbon salad"},{"name":"salt","amount":"1/4 tsp","notes":"for ribbon salad"}]', '1. Prepare Tofu and Noodles: Press *extra-firm tofu* for at least 15 minutes to remove excess water, then cut into 1.5 cm cubes. Soak *rice stick noodles* in warm water for 15-20 minutes until pliable but still firm (al dente); drain and set aside.
2. Make Pad Thai Sauce: In a small bowl, whisk together *tamarind paste*, *soy sauce*, *maple syrup*, and *rice vinegar*. Set aside.
3. Sauté *tofu* and Aromatics: Heat 1 tbsp of *vegetable oil* in a large wok or frying pan over medium-high heat. Add cubed tofu and cook, stirring occasionally, until golden brown and slightly crispy on all sides, about 5-7 minutes. Remove tofu from the pan and set aside. Add the remaining 1 tbsp of oil to the pan. Add minced *garlic* and sauté for 30 seconds until fragrant.
4. Stir-fry Vegetables: Add julienned *carrot*, thinly sliced *red bell pepper*, and small *broccoli florets* to the pan. Stir-fry for 3-4 minutes until vegetables are tender-crisp.
5. Combine and Finish Pad Thai: Add the soaked and drained rice *noodles* to the pan with the vegetables. Pour the prepared Pad Thai *sauce* over the noodles and vegetables. Toss everything together vigorously for 2-3 minutes until the noodles are well coated and heated through. Add the cooked *tofu*, *bean sprouts*, and sliced *spring onions*. Toss for another minute until bean sprouts are slightly wilted and all ingredients are combined.
6. Prepare *cucumber*-*lime* Ribbon Salad: While the Pad Thai is finishing, use a vegetable peeler to create long ribbons from the cucumber. In a small bowl, gently toss the cucumber ribbons with *lime juice* and a pinch of *salt*.
7. Serve: Divide the Veggie Pad Thai among serving plates. Garnish generously with *crushed roasted peanuts*, *fresh coriander*, and *lime* wedges. Serve immediately with the refreshing *cucumber*-lime ribbon salad on the side.', 'recipe-images/veggie-pad-thai.jpg', array['thai', 'vegan']),
  ('weeknight-beef-chili', 'Weeknight Beef Chili', 'Ground beef chili with beans, tomatoes, and smoky spices, paired with baked sweet potato fries.', '[{"name":"olive oil","amount":"1 tbsp","notes":"for chili"},{"name":"lean ground beef","amount":"500g"},{"name":"onion","amount":"1 large","notes":"diced"},{"name":"garlic","amount":"3 cloves","notes":"minced"},{"name":"chili powder","amount":"2 tbsp"},{"name":"ground cumin","amount":"1 tbsp"},{"name":"smoked paprika","amount":"1 tsp"},{"name":"cayenne pepper","amount":"1/2 tsp","notes":"optional, for extra heat"},{"name":"salt","amount":"1 tsp","notes":"for chili"},{"name":"black pepper","amount":"1/2 tsp","notes":"for chili"},{"name":"diced tomatoes","amount":"400g","notes":"undrained"},{"name":"kidney beans","amount":"400g","notes":"rinsed and drained"},{"name":"black beans","amount":"400g","notes":"rinsed and drained"},{"name":"beef broth","amount":"250ml"},{"name":"sweet potatoes","amount":"2 medium","notes":"about 500g"},{"name":"olive oil","amount":"1 tbsp","notes":"for sweet potato fries"},{"name":"salt","amount":"1/2 tsp","notes":"for sweet potato fries"},{"name":"shredded cheddar cheese","amount":"as desired","notes":"optional garnish"},{"name":"sour cream","amount":"as desired","notes":"optional garnish"},{"name":"fresh cilantro","amount":"as desired","notes":"chopped, optional garnish"}]', '1. Preheat oven to 200°C. Line a large baking sheet with parchment paper.
2. Peel *sweet potatoes* and cut them into fries about 1 cm thick. In a bowl, toss the sweet potato fries with 1 tbsp *olive oil* and 1/2 tsp *salt*. Spread them in a single layer on the prepared baking sheet and bake for 25-30 minutes, flipping halfway through, until tender and lightly browned.
3. While the *sweet potatoes* bake, heat 1 tbsp *olive oil* in a large pot or Dutch oven over medium-high heat. Add the *ground beef* and cook, breaking it up with a spoon, until it is fully browned, about 5-7 minutes. Drain any excess fat.
4. Add the diced *onion* to the pot with the *beef* and cook until softened, about 3-5 minutes. Stir in the minced *garlic*, *chili powder*, *ground cumin*, *smoked paprika*, *cayenne pepper* (if using), 1 tsp *salt*, and 1/2 tsp *black pepper*. Cook for 1 minute more, stirring constantly, until fragrant.
5. Stir in the undrained *diced tomatoes*, rinsed and drained *kidney beans*, rinsed and drained *black beans*, and *beef* broth. Bring the mixture to a simmer, then reduce the heat to low, cover, and let it simmer for 15-20 minutes, stirring occasionally, to allow the flavors to meld.
6. Taste the chili and adjust seasonings if necessary. Serve the hot chili alongside the crispy baked sweet potato fries. Garnish with *shredded cheddar cheese*, a dollop of *sour cream*, and *fresh cilantro*, if desired.', 'recipe-images/weeknight-beef-chili.jpg', array['american', 'beef', 'spicy', 'glutenfree'])

on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  image_url = excluded.image_url,
  tags = excluded.tags;
